FEAT: Allow redirectedurls to apply to assets
silverstripe/silverstripe-redirectedurls pull request #80
Opened 2020-04-27 12:59 UTC by madmatt

This only applies if the `silverstripe/assets` module is installed, we don't require it for this module.

Note: Requires silverstripe/silverstripe-assets/pull/391 to be merged prior to merging this. As such we probably shouldn't merge this until that has been merged and a new stable released (so a new stable of this module can be released to coincide with it - although I don't think you can specify 'minimum version of a suggested module', right?)

2020-10-18 22:24 UTC, maxime-rainville requested changes
Haven't tested it locally. But at first glance it looks good.

Since the entire point of the PR is to redirect assets, I think we should have a test case that explicitly test that.

2020-10-18 22:24 UTC, maxime-rainville commented on src/Service/RedirectedURLService.php
> +class RedirectedURLService
Maybe define an interface for this service and add some documentation for the class.

2020-10-18 22:24 UTC, maxime-rainville commented on src/Service/RedirectedURLService.php
> +    protected function arrayToLowercase($vars)
Unless we explicitly expect people to extend this class and call this method, I would make it private to minimise our API surface.

2020-10-18 22:24 UTC, maxime-rainville commented on src/Service/RedirectedURLService.php
> +    public function getRedirectCode($redirectedURL = null)
Add a doc block and define return type.

2020-10-18 22:24 UTC, maxime-rainville commented on src/Extension/AssetStoreURLHandler.php
> + *
```suggestion
```

2020-10-18 22:24 UTC, maxime-rainville commented on src/Extension/RedirectedURLHandler.php
> -    protected function arrayToLowercase($vars)
That would be considered an API change.

2020-10-18 22:24 UTC, maxime-rainville commented on src/Extension/RedirectedURLHandler.php
> -    protected function getRedirectCode($redirectedURL = false)
That would be considered an API change.

2021-12-03 00:45 UTC, oddnoc commented
@madmatt Are you interested in pursuing this? Otherwise, I could take over the task.

2021-12-07 12:08 UTC, madmatt commented
Hey @oddnoc , feel free to do so if you want! I am using a fork for a recent project which I really need to get rid of, but I just haven't found the time recently. If you end up getting this updated and merged in I'd love to know about it!

Thank you!

2022-04-27 04:26 UTC, n8-dev commented
Since https://github.com/silverstripe/silverstripe-assets/pull/391 has been merged it would be great to get this merged in 🙏

2023-02-08 21:49 UTC, chrispenny commented
Closing as we'll continue this in #86

2023-02-08 21:49 UTC, closed without merging